### ISSUE TITLE
Intermittent invalid generated signatures

### ISSUE THREAD

**Issue by vlovgr** [xerial/sbt-sonatype#44] opened 2017-05-26 07:07 UTC
I'm using sbt-pgp together with sbt-sonatype and sbt-release (see [release settings](https://github.com/vlovgr/ciris/blob/master/build.sbt#L212)) to cross-build to Scala and Scala.js on 2.10, 2.11, and 2.12. Typically, everything goes fine until it's time to close the staging repository, when Sonatype complains that some artifacts (from what I've been able to see, it's usually different ones every time) have invalid signatures.

```
[info] Closing staging repository [iscir-1012] status:open, profile:is.cir(60b94b73626074) description: Implicitly created (auto staging).
[info] Activity open started:2017-05-25T21:49:47.982Z, stopped:2017-05-25T21:49:52.357Z
[info] repositoryCreated: id:iscir-1012, user:vlovgr
[info] Activity close started:2017-05-25T21:54:54.041Z, stopped:2017-05-25T21:55:17.322Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-enumeratum_2.11/0.3.1/ciris-enumeratum_2.11-0.3.1.jar.asc' is not a valid signature for 'ciris-enumeratum_2.11-0.3.1.jar'.
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:1
[info] repositoryCloseFailed: id:iscir-1012, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-05-25T22:11:15.116Z, stopped:2017-05-25T22:11:29.844Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: signature-staging
[info]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-enumeratum_2.10/0.3.1/ciris-enumeratum_2.10-0.3.1-javadoc.jar.asc' is not a valid signature for 'ciris-enumeratum_2.10-0.3.1-javadoc.jar'.
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:1
[info] repositoryCloseFailed: id:iscir-1012, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-05-25T22:21:08.093Z, stopped:2017-05-25T22:21:31.755Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: signature-staging
[info]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-core_2.12/0.3.1/ciris-core_2.12-0.3.1.jar.asc' is not a valid signature for 'ciris-core_2.12-0.3.1.jar'.
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:1
[info] repositoryCloseFailed: id:iscir-1012, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-05-25T22:31:35.700Z, stopped:2017-05-25T22:31:52.635Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: signature-staging
[info]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-squants_sjs0.6_2.11/0.3.1/ciris-squants_sjs0.6_2.11-0.3.1-javadoc.jar.asc' is not a valid signature for 'ciris-squants_sjs0.6_2.11-0.3.1-javadoc.jar'.
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:1
[info] repositoryCloseFailed: id:iscir-1012, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-05-25T23:12:13.660Z, stopped:
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-generic_2.11/0.3.1/ciris-generic_2.11-0.3.1-sources.jar.asc' is not a valid signature for 'ciris-generic_2.11-0.3.1-sources.jar'.
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: checksum-staging
[error] Failed to close the repository
[error] Activity close started:2017-05-25T23:12:13.660Z, stopped:
[error]     Failed: signature-staging, failureMessage:Invalid Signature: '/is/cir/ciris-generic_2.11/0.3.1/ciris-generic_2.11-0.3.1-sources.jar.asc' is not a valid signature for 'ciris-generic_2.11-0.3.1-sources.jar'.
java.lang.Exception: Failed to close the repository
	at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:717)
	at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:816)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:206)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:198)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbtrelease.ReleasePlugin$autoImport$$anonfun$releaseStepCommand$2.apply(ReleasePlugin.scala:94)
	at sbtrelease.ReleasePlugin$autoImport$$anonfun$releaseStepCommand$2.apply(ReleasePlugin.scala:92)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.sbtrelease$ReleasePlugin$autoImport$ReleaseKeys$$anonfun$$filterFailure$1(ReleasePlugin.scala:175)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$8$$anonfun$apply$3.apply(ReleasePlugin.scala:189)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$8$$anonfun$apply$3.apply(ReleasePlugin.scala:189)
	at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
	at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at scala.Function$$anonfun$chain$1.apply(Function.scala:24)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:193)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:156)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to close the repository
```

When this happens, I've manually tried to verify the local signatures of the failing artifacts with `gpg --verify` and it tells me that, indeed, the signatures are invalid. If repeating the release process from the beginning, after a few tries (sometimes up to 10 retries), it normally works just fine, and I'm able to close the staging repository successfully, without having to change anything.

**Comment by xerial** [comment] 2017-05-31 06:08
I'm not sure the cause of this error, but I usually run `publishSigned` command explicitly:
https://github.com/xerial/sbt-sonatype#using-with-sbt-release-plugin

Here is an example of my build.sbt, which cross builds a project for Scala 2.11, 2.12 and Scala.js:
https://github.com/wvlet/airframe/blob/a66789c2e13288bbc28819dca6bcb6acb498a8d0/build.sbt#L46

**Comment by vlovgr** [comment] 2017-06-01 12:36
Unfortunately, looks like this is still happening with the suggested release steps (https://github.com/vlovgr/ciris/pull/21).

The only real difference with your example and my settings, is that I use:
```
useGpg := true
```

**Comment by xerial** [comment] 2017-06-02 05:31
@vlovgr Probably I've seen a similar error with sbt-pgp 1.0.1 plugin and gpg 2.1.2 on Mac OS X.
It might be worth a try sbt-pgp-1.1.0-M1. My problem was fixed after upgrading sbt-pgp plugin.

**Comment by vlovgr** [comment] 2017-06-02 05:56
Indeed I'm running sbt-pgp 1.0.1 with GPG 2.1.21 on macOS. I've tried upgrading to sbt-pgp 1.1.0-M1 before with the same results. I can't remember why I set `useGpg := true` initially, but I believe it didn't work without it when I first set this up (now it worked without issues, though).

**Comment by xerial** [comment] 2019-09-05 05:13
I haven't seen this problem for a while with sbt-pgp-2.0.0-M2. Let me close this issue. If this still happens, reopen it or create a new ticket.

**Closed by xerial** 2019-09-05 05:13 UTC
